apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service-container
          image: wicky2001/order_service:051431f43d40fb945f15c6efdf7d1af2ef7ff011
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          envFrom:
            - secretRef:
                name: order-service-secret
            - configMapRef:
                name: order-service-config
