apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: app
data:
  DB_HOST: "ep-group-project-postgresql-server.postgres.database.azure.com" 
  DB_PORT: "5432"
  DB_NAME: "product_db"
  DB_SSL_MODE: "require"
  SPRINGDOC_API_DOCS_ENABLED: "false"
  SPRINGDOC_SWAGGER_UI_ENABLED: "false"