apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service-container
          image: wicky2001/product_service:4db2371b0ee98a0c95db9430a2188a32f4ec86d9
          image: wicky2001/product_service:4db2371b0ee98a0c95db9430a2188a32f4ec86d9
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: product-service-secret
            - configMapRef:
                name: product-service-config-map
