apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: app
spec:
  selector:
    app: product-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  template:
    spec:
      containers:
        - image: enterprisegroupprojectregistry.azurecr.io/product_service:d936e92572b37168551879fb4a6b9052d9e53982
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service-container
          image: enterprisegroupprojectregistry.azurecr.io/product_service:d936e92572b37168551879fb4a6b9052d9e53982
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: product-service-secret
            - configMapRef:
                name: product-service-config-map
