---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: product-service-secret
  namespace: app
spec:
  encryptedData:
    SPRING_DATASOURCE_PASSWORD: AgCFyKCuWuYF1daSc70xIvPMl9h+VDHjR3EhXeQedStDrfF+6QSCeJgG9hiSnnXcfSHuY4shPuUr6kNF+RbVyglBPJvysMmXGql3o+oRdmbJb2n5c18IQy6mEXFR9JjLMPIET5BzQh/42luf4r3Fk8wrhyx9k1axycDi0KQJ8UAW63g6Lt4oko3JHk87JwSXLSpHiJEaabWBhPIt3A9Xzf8ZDuMZDt/38AAgGdz9wbDHQSoSk/Uwz8DY6eBs0/IrOIHTKWdZWdgXN8B9v+b37+wcJc88KGjHgQykAfhN1topM7prZxLkupyPJdkJGY5zM503roBnouqywAzIWmglfdA6fG4Q29OdLca1mQGHv+X4h+nOQXnOZ4BrWoGiuF1sGELlgvoTQ9mHaS6aZ297OLjzq90MTWf8eLd5WjEdu3ymN6/ahUAz16M0CEkT7C33xkZbJdwMDXaJsCQ3zykI56bY2LJ/z8EsqVOD6aXW7iK71yzZV5/ssio3AJgfMS7uZweF3zGMU91R+dzztYmDnzY1OhpXgiIwEnMn6n03ZmN4ouxIdkmaj6QbYepseN4BQv6a8Jz9QF8wWfasEJzHfekcPZj1r9SgCo3Zyc/ekf3vQoKk+f3qSXoVCQM2Z/m7hAg42xUNvZlTOp1wInR/VIi2GYQKcZoKHCNydPEUzgEXiRiW3WoNOYWlSrW/08DTkuQNnCoE7prLFcGXb4cy3HUL
    SPRING_DATASOURCE_USERNAME: AgBwmuoVAvjA/szYvFwYp+rW7t+pFpv83FWXOkX8jfVRl90kz8uqZdux5ReiyC1VcyVKbQBQ+v9m3wnDI5U/QXVjmKX6UOyfQ59jVm06RePAOQMfxYohXCvoKsv+2yGl+KkkLYwV0rCTd7MSxrB2FDO/y71pGKCQTToFz19ALAEERUCywta24N4JN2tPP6K4/pzW1tWTwIsNcPkceAnHzH3Q8jnO63vxJH+0cOE9ue3Gw8FLIyaYyvkxpFPbpLTLT4ilZuIMdU9P+4dkiHFr/aaeyvzDoy/zg1K4qxM9+WztEUMDMmrkOswfqnG+pS6f3ROBN5BSJrkGSJXLU55bAi/X3FiflUC019rZplsZTHmBhL28HiVgPbwtCjE4lTm05tYX8qkqTTa8FwgR6JtA4RkIEuICts865MxogyYhmQz7uXw65Ceuq2PGVJ2NjyGdCA93DYiQ2tsQrRPVqFOX1+F9SZ2TzXNii49Bly+1D/CiytmvgCUn+3KMmxaXVGfpCM1MsEGs8nY61DI7gecY0I3gNCLMt99W9N/QBgysaZBQa/a1wjOp7EpVC31djQDbI3GevY0VuGkF2caZqlFI6GKkRjtaJ8HNG8w/uCW+7xkSrvHIwEwGYEYF4UMw1kCi+utyGqpsPGHFHBNVmRl4Y2uVbNw2GijHRL90cObok93jz2ykx3ZxBanovHlGQBMnjwhtpTY9xvGqxdhKPg1Vk4A=
  template:
    metadata:
      name: product-service-secret
      namespace: app
    type: Opaque
