apiVersion: v1
kind: Pod
metadata:
  name: pg-bastion
  namespace: app 
spec:
  containers:
  - name: postgres-client
    image: postgres:16-alpine
    command: ["sleep", "infinity"]
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  restartPolicy: Always