apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-product-service
  namespace: argocd
spec:
  project: ep-group-project
  source:
    repoURL: https://github.com/Ecommerce-Group-Project/git-ops.git
    targetRevision: main
    path: k8s/product_service # ◄ Points to your product manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: app # ◄ Deploys into your shared 'app' namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true